name: Static Analysis

on: ['push', 'pull_request']

jobs:

  phpstan:
    runs-on: ubuntu-latest

    name: PHPStan

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --prefer-dist --no-progress --ansi

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --ansi
